import { CommonModule } from '@angular/common';
import { CUSTOM_ELEMENTS_SCHEMA, NgModule } from '@angular/core';
import { RouterModule } from '@angular/router';
import { TranslocoRootModule } from '@app/transloco-root.module';
import {
  TuiAxesModule, TuiBarChartModule, TuiBarModule, TuiLineChartModule,
  TuiLineDaysChartModule,
  TuiPieChartModule,
  TuiRingChartModule
} from '@taiga-ui/addon-charts';
import {
  TuiCardModule, TuiCurrencyPipeModule,
  TuiInputCVCModule,
  TuiInputCardModule,
  TuiInputExpireModule,
  TuiMoneyModule
} from '@taiga-ui/addon-commerce';
import { TuiColorPickerModule } from '@taiga-ui/addon-editor';
import { HomePage } from './home.page';
// import { TuiDataListModule, TuiLoaderModule } from '@taiga-ui/core';
// import {
//   TuiActionModule, TuiComboBoxModule,
//   TuiDataListWrapperModule,
//   TuiToggleModule
// } from '@taiga-ui/kit';
import {
  TuiAutoFocusModule,
  TuiElementModule,
  TuiFilterPipeModule,
  TuiLetModule,
  TuiMapperPipeModule,
  TuiMediaModule
} from '@taiga-ui/cdk';
import {
  TUI_DIALOGS_CLOSE,
  TuiButtonModule,
  TuiCalendarModule,
  TuiDataListModule,
  TuiDialogModule,
  TuiDropdownControllerModule,
  TuiDropdownModule,
  TuiErrorModule,
  TuiExpandModule,
  TuiFormatNumberPipeModule,
  TuiFormatPhonePipeModule,
  TuiGroupModule,
  TuiHintControllerModule,
  TuiHintModule,
  TuiHostedDropdownModule,
  TuiLabelModule,
  TuiLinkModule,
  TuiLoaderModule,
  TuiManualHintModule,
  TuiModeModule,
  TuiNotificationModule,
  TuiNotificationsModule,
  TuiPointerHintModule,
  TuiPrimitiveCheckboxModule,
  TuiPrimitiveTextfieldModule,
  TuiRootModule,
  TuiScrollbarModule,
  TuiSvgModule, TuiTextfieldControllerModule,
  TuiTooltipModule
} from '@taiga-ui/core';
import {
  TuiAccordionModule,
  TuiActionModule,
  TuiAvatarModule,
  TuiBadgeModule,
  TuiBadgedContentModule,
  TuiBreadcrumbsModule,
  TuiCalendarMonthModule,
  TuiCalendarRangeModule,
  TuiCheckboxBlockModule,
  TuiCheckboxLabeledModule,
  TuiCheckboxModule,
  TuiComboBoxModule,
  TuiDataListWrapperModule,
  TuiDropdownSelectionModule,
  TuiFieldErrorModule, TuiFilterByInputPipeModule, TuiFilterModule,
  TuiHighlightModule,
  TuiInputCopyModule,
  TuiInputCountModule,
  TuiInputDateModule,
  TuiInputDateRangeModule,
  TuiInputDateTimeModule,
  TuiInputFileModule,
  TuiInputInlineModule,
  TuiInputModule,
  TuiInputMonthModule,
  TuiInputMonthRangeModule,
  TuiInputNumberModule,
  TuiInputPasswordModule,
  TuiInputPhoneInternationalModule,
  TuiInputPhoneModule,
  TuiInputRangeModule,
  TuiInputSliderModule,
  TuiInputTagModule,
  TuiInputTimeModule,
  TuiIslandModule,
  TuiLazyLoadingModule,
  TuiLineClampModule,
  TuiMarkerIconModule,
  TuiMultiSelectModule,
  TuiPaginationModule,
  TuiPresentModule,
  TuiProjectClassModule, TuiRadioBlockModule,
  TuiRadioLabeledModule,
  TuiRadioListModule,
  TuiRadioModule,
  TuiSelectModule,
  TuiSliderModule,
  TuiStepperModule,
  TuiTabsModule,
  TuiTagModule,
  TuiTextAreaModule,
  TuiToggleModule
} from '@taiga-ui/kit';
import { PolymorpheusModule } from '@tinkoff/ng-polymorpheus';
import { AuthService } from '../auth/services/auth.service';
@NgModule({
  declarations: [HomePage],
  providers: [
    {
      provide: TUI_DIALOGS_CLOSE,
      deps: [AuthService],
      useFactory: authService => authService.logout$,
    },
  ],
  schemas: [ CUSTOM_ELEMENTS_SCHEMA],
  imports: [
    CommonModule,
    TranslocoRootModule,
    TuiToggleModule,
    TuiComboBoxModule,
    TuiDataListWrapperModule,
    TuiDataListModule,
    TuiActionModule,
    TuiLoaderModule,
    CommonModule,
    TuiRootModule,
    TuiDialogModule,
    TuiNotificationsModule,
    TuiAccordionModule,
    TuiAvatarModule,
    TuiBadgeModule,
    TuiBadgedContentModule,
    TuiButtonModule,
    TuiCalendarModule,
    TuiCalendarRangeModule,
    TuiCalendarMonthModule,
    TuiCardModule,
    TuiAxesModule,
    TuiLineChartModule,
    TuiLineDaysChartModule,
    TuiPieChartModule,
    TuiBarChartModule,
    TuiRingChartModule,
    TuiCheckboxModule,
    TuiCheckboxBlockModule,
    TuiCheckboxLabeledModule,
    TuiPrimitiveCheckboxModule,
    TuiColorPickerModule,
    TuiHostedDropdownModule,
    TuiErrorModule,
    TuiFieldErrorModule,
    TuiExpandModule,
    TuiFilterModule,
    TuiGroupModule,
    TuiMarkerIconModule,
    TuiInputInlineModule,
    TuiInputModule,
    TuiInputDateModule,
    TuiInputCardModule,
    TuiInputCVCModule,
    TuiInputExpireModule,
    TuiInputCopyModule,
    TuiInputCountModule,
    TuiInputDateTimeModule,
    TuiInputFileModule,
    TuiInputMonthModule,
    TuiInputMonthRangeModule,
    TuiInputNumberModule,
    TuiInputPasswordModule,
    TuiInputPhoneModule,
    TuiInputRangeModule,
    TuiInputDateRangeModule,
    TuiInputTagModule,
    TuiInputTimeModule,
    TuiInputPhoneInternationalModule,
    TuiPrimitiveTextfieldModule,
    TuiTextAreaModule,
    TuiIslandModule,
    TuiLabelModule,
    TuiLineClampModule,
    TuiLinkModule,
    TuiNotificationModule,
    TuiRadioModule,
    TuiRadioBlockModule,
    TuiRadioLabeledModule,
    TuiRadioListModule,
    TuiMultiSelectModule,
    TuiSelectModule,
    TuiScrollbarModule,
    TuiInputSliderModule,
    TuiSliderModule,
    TuiSvgModule,


    TuiTagModule,
    TuiTooltipModule,
    TuiBreadcrumbsModule,
    TuiPaginationModule,
    TuiStepperModule,
    TuiTabsModule,
    TuiAutoFocusModule,
    TuiDropdownModule,
    TuiDropdownSelectionModule,

    TuiElementModule,
    TuiHighlightModule,
    TuiHintModule,
    TuiLazyLoadingModule,
    TuiManualHintModule,
    TuiPointerHintModule,
    TuiLetModule,
    TuiMediaModule,
    TuiModeModule,
    TuiPresentModule,


    TuiDropdownControllerModule,
    TuiHintControllerModule,
    TuiTextfieldControllerModule,
    TuiMoneyModule,
    PolymorpheusModule,
    TuiFilterPipeModule,
    TuiFormatNumberPipeModule,
    TuiFormatPhonePipeModule,
    TuiMapperPipeModule,

    TuiBarModule,
    TuiCurrencyPipeModule,
    TuiProjectClassModule,
    TuiFilterByInputPipeModule,
  
    RouterModule.forChild([
      {
        path: '',
        component: HomePage,

        data: {
          title: 'Home',
          description:
            'Angular starter for enterprise-grade front-end projects, built under a clean architecture that helps to scale and maintain a fast workflow.',
          robots: 'index, follow',
        },
      },
    ]),
  ],
})
export class HomeModule {}
